version: '3'

services:
  db:
    image: postgres:alpine
    ports:
      - "15432:5432"
    volumes: 
      - pg-data:/var/lib/postgresql/data
  graphite:
    image: sitespeedio/graphite
    ports:
      - "8080:80"
  statsdaemon:
    image: ctdk/statsdaemon
    depends_on:
      - graphite
  fakes3:
    image: lphoward/fake-s3
    ports:
      - "4569:4569"
    volumes:
      - s3:/s3-root
  webui:
    image: ctdk/webui
    ports:
      - "3000:3000"
    volumes:
      - ./goiardi-etc:/etc/goiardi
  nginx:
    image: nginx:1.12.0-alpine
    ports:
      - "80:80"
  goiardi:
    image: ctdk/goiardi:auth-1.3
    env_file: ./postgres.env
    ports:
      - "4545:4545"
    volumes:
      - ./goiardi-etc:/etc/goiardi
      - goiardi-lib:/var/lib/goiardi
    depends_on:
      - db
      - statsdaemon

volumes:
  pg-data:
  goiardi-lib:
  s3:
