version: '3'

services:
  db:
    image: postgres:alpine
    ports:
      - "15432:5432"
    volumes: 
      - pg-data:/var/lib/postgresql/data
  goiardi:
    image: ctdk/goiardi:auth-1.3
    env_file: ./env.list
    ports:
      - "4545:4545"
    volumes:
      - ./goiardi-etc:/etc/goiardi
      - goiardi-lib:/var/lib/goiardi
    depends_on:
      - db

volumes:
  pg-data:
  goiardi-lib:
